blank_issues_enabled: false
contact_links:
  - name: Slam Mirrorbot Channel
    url: https://t.me/+_RkFEtelcrQ1MzI1
    about: Update Channel
  - name: Slam Mirrorbot Group
    url: https://t.me/+iCgxgbD5sY8yODk1
    about: Support Group
  - name: Bug Report Group
    url: https://t.me/JappeRoot
    about: Bug Report & Feature Request Group
